### ISSUE TITLE
Make Linux / make win

### ISSUE THREAD

**Issue by Pav-Bahia** [sassoftware/viya4-orders-cli#14]
Hi 
I may have missed a point here, but i have tried to test out the make command.
make win = works when run from CMD
make linux = fails when run from bash shell
viya4-orders-cli_linux_amd64: command not found
am i missing a step..

**Comment by sarahcpage** [comment]
Hi,

I cannot reproduce your problem with _make linux_. I am running _CentOS Linux release 7.9.2009 (Core)_ and _GNU Make 3.82 Built for x86_64-redhat-linux-gnu_
-what distribution / release of Linux are you running?
-what version of Make (please run _make --version_)?
-since _make linux_ failed, _viya4-orders-cli_linux_amd64: command not found_ is to be expected (_viya4-orders-cli_linux_amd64_ is the executable that results from the _make linux_ command)

Thank you for using viya4-orders-cli!

**Comment by Pav-Bahia** [comment]
reloaded a new Vbox image using centos and it worked
